/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GameScene from "./scenes/GameScene"
import GameControlNew from "./script/GameControlNew"
import StartScene from "./scenes/StartScene"
import GameUI from "./script/GameUI"
import GameControl from "./script/GameControl"
import Bullet from "./script/Bullet"
import Column from "./script/Column"
import DropBox from "./script/DropBox"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("scenes/GameScene.js",GameScene);
		reg("script/GameControlNew.js",GameControlNew);
		reg("scenes/StartScene.js",StartScene);
		reg("script/GameUI.js",GameUI);
		reg("script/GameControl.js",GameControl);
		reg("script/Bullet.js",Bullet);
		reg("script/Column.js",Column);
		reg("script/DropBox.js",DropBox);
    }
}
GameConfig.width = 640;
GameConfig.height = 1136;
GameConfig.scaleMode ="fixedheight";
GameConfig.screenMode = "vertical";
GameConfig.alignV = "middle";
GameConfig.alignH = "center";
GameConfig.startScene = "test/GameScene.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
